### PR TITLE
Typo in Code of Conduct

### PR DESCRIPTION
**Pull request by pearlchen**
Minor typo fix. Only noticed because I was cribbing my CoC off yours. :)

[Review on Reviewable](https://reviewable.io/reviews/angular/code-of-conduct/2)

### CODE REVIEW

**Comment by danielhickman** [comment]
Will solve #1

**Comment by beporter** [comment]
Is there something holding this up from getting merged? Why the 5 month wait for a typo fix?

**Comment by aloisdg** [comment]
It would be nice to fix this one.

**Comment by beporter** [comment]
Maybe none of the maintainers are getting notifications about this project (which seems bad, but whatever.)

So let's trying pinging the last person to commit directly: @btford, can you help us out here?

**Comment by aloisdg** [comment]
Its a minor fix :)

**Comment by robwormald** [comment]
apologies it took so long, i've got admin rights on this now (and notifications on...) - fixed in https://github.com/angular/code-of-conduct/commit/89346bf3f80795bd210ff98853af8ec4e3c05a45

**Pull request closed without merging**
